{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "afservice.fullname" . }}-hpa
spec:
  maxReplicas: {{ .Values.hpa.maxReplicaCount }}
  minReplicas: {{ .Values.replicaCount }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "afservice.fullname" . }}
  targetCPUUtilizationPercentage: 25
{{- end }}
